// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2oqDI9D5qBQV4KrUPMdJagE1SPZnklZw',
    appId: '1:215515104048:web:e7f11cb2b9c3db08e67ef5',
    messagingSenderId: '215515104048',
    projectId: 'mainor-2026-spring-half-full',
    authDomain: 'mainor-2026-spring-half-full.firebaseapp.com',
    storageBucket: 'mainor-2026-spring-half-full.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxgYO4FZaPVtuk8eq2trzeCCPFKGLid4',
    appId: '1:215515104048:android:5b42f6835e00d534e67ef5',
    messagingSenderId: '215515104048',
    projectId: 'mainor-2026-spring-half-full',
    storageBucket: 'mainor-2026-spring-half-full.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG0Z2E72gR-sVzSTmkCkLltwHWycCth1Y',
    appId: '1:215515104048:ios:675d5130c684f9ebe67ef5',
    messagingSenderId: '215515104048',
    projectId: 'mainor-2026-spring-half-full',
    storageBucket: 'mainor-2026-spring-half-full.firebasestorage.app',
    iosBundleId: 'com.mainor.halffull.halfFull',
  );
}
